

loader_params: 

    'train_bs': 1
    'val_bs': 1
    'csv_root': 'meta_files/meta_data_infer_val.csv'
    'scale_dose_dict': 'meta_files/PTV_DICT.json'
    'pat_obj_dict': 'meta_files/Pat_Obj_DICT.json'
    'num_workers': 2

    'down_HU': -1000
    'up_HU': 1000
    'denom_norm_HU': 500

    'in_size': [96, 128, 144]
    'out_size': [96, 128, 144]

    'norm_oar': True
    'CatStructures': False
    'dose_div_factor': 10 
    
    
model_params:
    num_input_channels: 8
    out_channels: 1
    model_id: 'B'
    kernel_size: 3
    deep_supervision: False

lr: 0.0001
num_epochs: 400

act_sig: True
scale_out: 7.5

# model_from_lightning: True
# save_model_path: ../pretrainmodel/GDP-HMM_Challenge/lightning/best_model-epoch=270-val_loss=0.2323.ckpt
# save_pred_path: '../pretrainmodel/GDP-HMM_Challenge/lightning/results'

model_from_lightning: True
save_model_path: ../pretrainmodel/GDP-HMM_Challenge/lightning_update/best_model-epoch=332-val_loss=0.2249.ckpt
save_pred_path: '../pretrainmodel/GDP-HMM_Challenge/lightning_update/results_val'


# model_from_lightning: False
# save_model_path: ../pretrainmodel/GDP-HMM_Challenge/last_model.pth
# save_pred_path: 'results'